//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: heddokoPacket.proto
namespace heddoko
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImuDataFrame")]
  public partial class ImuDataFrame : global::ProtoBuf.IExtensible
  {
    public ImuDataFrame() {}
    
    private uint _imuId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"imuId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint imuId
    {
      get { return _imuId; }
      set { _imuId = value; }
    }
    private uint _sensorMask = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sensorMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sensorMask
    {
      get { return _sensorMask; }
      set { _sensorMask = value; }
    }
    private float _quat_x_yaw = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"quat_x_yaw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float quat_x_yaw
    {
      get { return _quat_x_yaw; }
      set { _quat_x_yaw = value; }
    }
    private float _quat_y_pitch = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quat_y_pitch", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float quat_y_pitch
    {
      get { return _quat_y_pitch; }
      set { _quat_y_pitch = value; }
    }
    private float _quat_z_roll = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quat_z_roll", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float quat_z_roll
    {
      get { return _quat_z_roll; }
      set { _quat_z_roll = value; }
    }
    private float _quat_w = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"quat_w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float quat_w
    {
      get { return _quat_w; }
      set { _quat_w = value; }
    }
    private int _Mag_x = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Mag_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Mag_x
    {
      get { return _Mag_x; }
      set { _Mag_x = value; }
    }
    private int _Mag_y = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Mag_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Mag_y
    {
      get { return _Mag_y; }
      set { _Mag_y = value; }
    }
    private int _Mag_z = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Mag_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Mag_z
    {
      get { return _Mag_z; }
      set { _Mag_z = value; }
    }
    private int _Accel_x = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Accel_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Accel_x
    {
      get { return _Accel_x; }
      set { _Accel_x = value; }
    }
    private int _Accel_y = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Accel_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Accel_y
    {
      get { return _Accel_y; }
      set { _Accel_y = value; }
    }
    private int _Accel_z = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Accel_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Accel_z
    {
      get { return _Accel_z; }
      set { _Accel_z = value; }
    }
    private int _Rot_x = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Rot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Rot_x
    {
      get { return _Rot_x; }
      set { _Rot_x = value; }
    }
    private int _Rot_y = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Rot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Rot_y
    {
      get { return _Rot_y; }
      set { _Rot_y = value; }
    }
    private int _Rot_z = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Rot_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Rot_z
    {
      get { return _Rot_z; }
      set { _Rot_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullDataFrame")]
  public partial class FullDataFrame : global::ProtoBuf.IExtensible
  {
    public FullDataFrame() {}
    
    private uint _timeStamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
    private readonly global::System.Collections.Generic.List<heddoko.ImuDataFrame> _imuDataFrame = new global::System.Collections.Generic.List<heddoko.ImuDataFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"imuDataFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<heddoko.ImuDataFrame> imuDataFrame
    {
      get { return _imuDataFrame; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Packet")]
  public partial class Packet : global::ProtoBuf.IExtensible
  {
    public Packet() {}
    
    private heddoko.PacketType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public heddoko.PacketType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private heddoko.Packet.BrainPackState _state = heddoko.Packet.BrainPackState.Idle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(heddoko.Packet.BrainPackState.Idle)]
    public heddoko.Packet.BrainPackState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _brainPackVersion = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"brainPackVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string brainPackVersion
    {
      get { return _brainPackVersion; }
      set { _brainPackVersion = value; }
    }
    private int _batteryCharge = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"batteryCharge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int batteryCharge
    {
      get { return _batteryCharge; }
      set { _batteryCharge = value; }
    }
    private heddoko.FullDataFrame _fullDataFrame = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fullDataFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public heddoko.FullDataFrame fullDataFrame
    {
      get { return _fullDataFrame; }
      set { _fullDataFrame = value; }
    }
    private string _recordingName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"recordingName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string recordingName
    {
      get { return _recordingName; }
      set { _recordingName = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BrainPackState")]
    public enum BrainPackState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Idle", Value=0)]
      Idle = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Recording", Value=1)]
      Recording = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Reset", Value=2)]
      Reset = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=4)]
      Error = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PacketType")]
    public enum PacketType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"StateRequest", Value=0)]
      StateRequest = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StateResponse", Value=1)]
      StateResponse = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DataFrame", Value=2)]
      DataFrame = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatteryChargeRequest", Value=3)]
      BatteryChargeRequest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatteryChargeResponse", Value=4)]
      BatteryChargeResponse = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BrainPackVersionRequest", Value=5)]
      BrainPackVersionRequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BrainPackVersionResponse", Value=6)]
      BrainPackVersionResponse = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetRecordingName", Value=7)]
      SetRecordingName = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRecordingName", Value=8)]
      GetRecordingName = 8
    }
  
}